version: '3.7'
services:
  application:
    image: ${PROJECT}:${GIT_LOCAL_BRANCH}
    container_name: ${PROJECT}
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    expose:
      - '8080'
    networks:
      - app
networks:
  app:
    driver: 'bridge'
